---
title: "Motivations"
format: html
editor: visual
---

One motivation for this research stems from an increasing scientific interest in understanding how microbial communities influence and are influenced by different ecosystems and environmental factors. We will be focusing our study on Alphaproteobacteria and the Chase Lake Wetlands. Wetlands serve crucial ecological functions, including water filtration and carbon storage, and microbes are at the heart of these processes. These microbial communities, like Alphaproteobacteria, are sensitive to environmental changes and are able to provide early warning signs of ecosystem stress or degradation. Another one of our motivating reasons is the environmental impact. Studying these microorganisms can help predict the impacts of environmental changes on wetland and other environments' health and can inform conservation strategies. The Chase Lake Wetlands serve as an important case study due to their unique ecological characteristics and the pressures they face from agricultural runoff and climate change.
